### PR TITLE
Feature/adapter changes

### PR DESCRIPTION
**Pull request by mazenrashed**
Give users the ability to add, delete, modify and replace one item without rerendering all items, and give the user a better feeling by giving the recycler view the ability to animate changes.

### CODE REVIEW

**Comment by mazenrashed** [comment]
Hi Ahmed, please make a review for the pull request

**Comment by mazenrashed** [comment]
Hi Ahmed, please don't forget to review the pull request, it's very helpful to users, thank you.

**Comment by mazenrashed** [comment]
Hi Ahmed,
Please don't forget to review the pull request.

**Comment by mazenrashed** [comment]
Hi Ahmed,
Please don't forget to review the pull request.

**Review by ahmedrizwan — APPROVED** [review]

**Comment by mazenrashed** [comment]
Thank you for approval, will you merge the branch and make a release ?

**Comment by ahmedrizwan** [comment]
@mazenrashed I'll merge and make a release over this weekend

**Comment by mazenrashed** [comment]
Ok, Thank you.

**Pull request merged**
